language: python
python:
  - "2.7"
  - "pypy"
  - "3.3"
before_install:
  - sudo apt-get update
  - sudo apt-get install libcurl4-gnutls-dev librtmp-dev
install:
  - pip install pycurl flake8
  - pip install mock
  - pip install six
  - python setup.py install
script:
  - python -W always setup.py test
